name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the package
        run: yarn build

      - name: Configure Git
        run: |
          git config --local user.email "sarmaged@gmail.com"
          git config --local user.name "Sarmaged"

      - name: Create new branch
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          NEW_BRANCH=release-v${NEW_VERSION}
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV

      - name: Update version in package.json
        run: |
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > temp.json && mv temp.json package.json

      - name: Create, commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b ${NEW_BRANCH}
          git diff
          git add .
          git commit -m "chore(release): update version to ${NEW_VERSION}"
          git push origin $NEW_BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update version to ${NEW_VERSION} and upgrade dependencies"
          branch: ${{ env.NEW_BRANCH }}
          base: main
          title: "Release ${NEW_VERSION}"
          body: "This PR updates the version to ${NEW_VERSION} and upgrades dependencies."
          labels: release
          auto-merge: true
          merge-method: squash
