name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Build the package
        run: yarn build

      - name: Configure Git
        run: |
          git config --local user.email "sarmaged@gmail.com"
          git config --local user.name "Sarmaged"

      - name: Delete existing tag
        run: |
          git tag -d ${GITHUB_REF#refs/tags/} || true
          git push origin :refs/tags/${GITHUB_REF#refs/tags/} || true

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Bump version and publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn version --new-version ${GITHUB_REF#refs/tags/v}
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          yarn publish --new-version ${GITHUB_REF#refs/tags/v}

      - name: Push changes back to GitHub and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b temp-branch
          git pull origin temp-branch || true
          git push origin temp-branch --follow-tags
          gh pr create --title "Auto-update version to ${GITHUB_REF#refs/tags/v}" --body "This PR was automatically created by GitHub Actions to update the version to ${GITHUB_REF#refs/tags/v}." --base main --head temp-branch
          gh pr merge --auto --squash temp-branch

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Describe your changes here
          draft: false
          prerelease: false
