name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Configure Git
        run: |
          git config --local user.email "sarmaged@gmail.com"
          git config --local user.name "Sarmaged"

      - name: Create new branch
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          git checkout -b auto-update-v${NEW_VERSION}

      - name: Update version in package.json
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > temp.json && mv temp.json package.json

      - name: Commit version change
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add package.json
          git commit -m "Update version to ${GITHUB_REF#refs/tags/v}"
          git push origin auto-update-v${GITHUB_REF#refs/tags/v}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Update version to ${GITHUB_REF#refs/tags/v} and upgrade dependencies"
          branch: auto-update-v${{ github.ref_name }}
          base: main
          title: "Update version to ${GITHUB_REF#refs/tags/v}"
          body: "This PR updates the version to ${GITHUB_REF#refs/tags/v} and upgrades dependencies."

      - name: Merge Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pr = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `auto-update-v${{ github.ref_name }}`,
              state: 'open',
            });

            if (pr.data.length > 0) {
              const pr_number = pr.data[0].number;
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
                merge_method: 'squash',
              });
            }

      - name: Build the package
        run: yarn build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          yarn publish --new-version ${GITHUB_REF#refs/tags/v}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Describe your changes here
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin --delete auto-update-v${{ github.ref_name }}
