name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Configure Git
        run: |
          git config --local user.email "sarmaged@gmail.com"
          git config --local user.name "Sarmaged"

      - name: Create new branch
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          git checkout -b auto-update-v${NEW_VERSION}

      - name: Update version in package.json
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > temp.json && mv temp.json package.json

      - name: Commit version change
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add package.json
          git add helpers.css
          git commit -m "Update version to ${GITHUB_REF#refs/tags/v}"
          git pull --rebase origin main
          git push origin auto-update-v${GITHUB_REF#refs/tags/v}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Update version to ${GITHUB_REF#refs/tags/v} and upgrade dependencies"
          branch: auto-update-v${NEW_VERSION}
          base: main
          title: "Update version to ${GITHUB_REF#refs/tags/v}"
          body: "This PR updates the version to ${GITHUB_REF#refs/tags/v} and upgrades dependencies."
          auto-merge: true
          merge-method: squash

      - name: Build the package
        run: yarn build

      - name: Install Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install GitHub CLI
        run: |
          brew install gh

      - name: Delete existing tag
        run: |
          git tag -d v${GITHUB_REF#refs/tags/v} || true
          git push origin :refs/tags/v${GITHUB_REF#refs/tags/v} || true

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          yarn publish --new-version $NEW_VERSION

      - name: Delete branch
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          BRANCH_NAME=auto-update-v${GITHUB_REF#refs/tags/v}
          git push origin --delete $BRANCH_NAME
