name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: yarn install

      - name: Configure Git
        run: |
          git config --local user.email "sarmaged@gmail.com"
          git config --local user.name "Sarmaged"

      - name: Create new branch
        run: |
          NEW_BRANCH="auto-update-${GITHUB_REF#refs/tags/}"
          git checkout -b $NEW_BRANCH

      - name: Update version in package.json
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          jq --arg new_version "$NEW_VERSION" '.version = $new_version' package.json > temp.json && mv temp.json package.json

      - name: Commit and push version change
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add package.json
          git commit -m "Update version to ${GITHUB_REF#refs/tags/v}"
          git push origin $NEW_BRANCH

      - name: Build the package
        run: yarn build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          yarn publish --new-version ${GITHUB_REF#refs/tags/v}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Update version to ${GITHUB_REF#refs/tags/v} and upgrade dependencies"
          branch: $NEW_BRANCH
          title: "Update version to ${GITHUB_REF#refs/tags/v}"
          body: "This PR updates the version to ${GITHUB_REF#refs/tags/v} and upgrades dependencies."

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Describe your changes here
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
