name: Build and Publish Vue Project

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update version in package.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          jq --arg new_version "$VERSION" '.version = $new_version' package.json > package.tmp.json && mv package.tmp.json package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Yarn build
        run: yarn build

      - name: Remove existing tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          git tag -d $TAG
          git push origin :refs/tags/$TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push updated files
        run: |
          git add .
          git commit -m "chore(release): update version to ${GITHUB_REF#refs/tags/}"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up NPM auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
